### ISSUE TITLE
MeetNinja shows "Failed!"

### ISSUE THREAD

**Issue by T4R1Q05** [SHUR1K-N/MeetNinja-Google-Meet-Bot#16] opened 2021-01-24 18:08 UTC
I don't know what the issue is.

**Comment by T4R1Q05** [comment] 2021-01-24 18:09
sorry forgot to install requirements.

**Comment by T4R1Q05** [comment] 2021-01-24 18:11
OOPSS it dosen't work

**Comment by SHUR1K-N** [comment] 2021-01-24 18:16
Have you tried everything from the "Possible fixes" section that is displayed upon failure?

If you have, you may open MeetNinja.py using an editor and uncomment [line #279](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/blob/4b700045a97e7862863e90e4163ac99f0cd59234/MeetNinja.py#L279) (fom `# print(e)` to just `print(e)`). Then, save the file and re-run it. This time, the failure will show itself in the form of a detailed traceback (error message) in the MeetNinja console window. You may then share this traceback here.

PS: You may not have added the `BROWSER_DRIVER` value. I am closing this Issue as this has been tested on multiple Linux machines at my end and everything works as intended and expected. If you have another valid issue, do open a fresh Issue.

**Closed as completed** 2021-01-24 20:28 UTC
Labels: invalid
