### ISSUE TITLE
Google blocks automated bots from logging into gmail accounts

### ISSUE THREAD

**Issue by skipperuzumaki** [SHUR1K-N/MeetNinja-Google-Meet-Bot#2] opened 2020-09-21 06:48 UTC

**Comment by SHUR1K-N** [comment] 2020-09-21 08:27
As of one minute ago, MeetNinja works perfectly (at least for me). This tool works with an approach of natural human interactions (sending mouse clicks and keyboard keystrokes), so it is highly unlikely to be "blocked" as you mentioned since as far as the browser is concerned, a human is interacting with it. Could you elaborate on what causes this blocking behavior on your side? A video would be wonderful. Thanks.

**Comment by skipperuzumaki** [comment] 2020-09-21 13:13
[video.zip](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/files/5255506/video.zip)
video of operation

**Comment by SHUR1K-N** [comment] 2020-09-21 13:18
This typically happens when you use such ambiguous and nonexistent account addresses (eg: testemail@mail.com, etc.). Have you tried a logging in with valid credentials? Input your valid account credentials and it should log into the account just fine. Do report back. Thanks.

PS: Just as reference, I have tested this on multiple Windows systems locally, externally, and with different Gmail accounts as well; all within the span of 2-3 days.

**Comment by skipperuzumaki** [comment] 2020-09-21 14:39
I did test on my valid gmail account switched it out to a dummy address to protect privacy.
It may be specific to my device ill do some testing and report back.

**Comment by SHUR1K-N** [comment] 2020-09-21 14:42
That is very strange. May be a stupid question, but have you logged in normally before with this e-mail address on this device successfully through the regular Chrome browser? Yes, please do report. Thanks.

**Comment by anjannair** [comment] 2020-09-21 17:07
> 
> 
> I did test on my valid gmail account switched it out to a dummy address to protect privacy.
> It may be specific to my device ill do some testing and report back.

If your dummy account is just weeks old then there's a high chance it will get blocked. Use the normal account you usually login through and try. It should work. Its probably a security measure to prevent automated spam.

**Comment by skipperuzumaki** [comment] 2020-09-21 18:11
to answer previous questions yes i have logged in that device with my google account previously 
the dummy account is not an actual account its just placeholder text for representation porpuses the actual account gives the same result
ibsuspect region locking but i need to test the app on other devices to confirm that theory
ps : im operating from india

**Comment by SHUR1K-N** [comment] 2020-09-25 23:55
I can confirm that MeetNinja works perfectly fine on standard Google accounts in India; tested on multiple accounts created approximately two months ago. As @anjannair suggested, this may just be a restriction for relatively new(er) accounts. 

However, I will wait for your tests' results to double-confirm this theory and possibly close this issue.

**Comment by skipperuzumaki** [comment] 2020-09-26 03:59
i havent been able to isolate the issue i am facing i think its better to close the issue for now if i have a breakthrough ill reopen

**Comment by 53X** [comment] 2020-10-07 21:01
i am seeing the exact same issue. Operating from India.

**Comment by SHUR1K-N** [comment] 2020-10-08 04:04
Could you share a screenshot of what the Google page shows upon execution? Also, do you have the latest iteration of MeetNinja?

**Comment by 53X** [comment] 2020-10-09 12:49
![Screenshot from 2020-10-08 18-11-30](https://user-images.githubusercontent.com/36399781/95584875-014ca000-0a5c-11eb-88a2-1e7c22614ba5.png)

**Comment by 53X** [comment] 2020-10-09 12:51
So it goes alright uptil this point and then stops ... i am already signed in to google ..... so i skipped the google sign in part in the code

**Comment by SHUR1K-N** [comment] 2020-10-09 13:18
You _need_ the signing in part included in the code because the new developer window of your selected browser that is generated with MeetNinja does _not_ not share any saved credentials from your _regular_ browser. The generated browser is an independent entity in itself.

Also, make sure the machine you are using _has_ been signed in to before a couple of times using this same Gmail address. Or else, extra layers like 2FA hinder the automated sign-in as Google needs to trust you and your "new" sign-in machine/location

Lastly, have you tried all the possible fixes mentioned in the MeetNinja window? And just confirming, do you have the latest iteration of MeetNinja? Because many newer commits have improved MeetNinja significantly with respect to its dynamic behavior. So, just in case you have an older version, _do_ try the latest commit and report back.

**Comment by SHUR1K-N** [comment] 2020-10-18 09:17
**[Closed]** Reason: Lack of follow-up/response. Do open/re-open if or when you are able to reproduce this issue even after the provided information.

**Closed as completed by SHUR1K-N** 2020-10-18 09:17 UTC
Labels: duplicate
